server:
  port: 9200
spring:
  redis:
    database: 10
    host: 118.31.251.4
    port: 6379
    password: # 如果未单独配置默认为空即可
    

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.251.4:3306/zjut?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Huan1997.
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  cache:
    type: redis
logging:
  level:
    com.zhm.drug.mapper: debug